[semver:minor] check if workflow failed

diff --git a/src/commands/wait_for_workflow.yml b/src/commands/wait_for_workflow.yml
--- a/src/commands/wait_for_workflow.yml
+++ b/src/commands/wait_for_workflow.yml
@@ -133,6 +133,14 @@ steps:
         while true; do
           get_num_running_workflows
           if [[ $total_workflows_running == "0" || $can_i_run == "true" ]]; then
+            # Check if workflow we have waited for finished successfully.
+            curl -s --request GET --url "$wf_url" --header "Circle-Token: ${CIRCLE_TOKEN}" > /tmp/swissknife/"wf_$1"_finished.json
+            finished_wf_status=$(jq .status < /tmp/swissknife/"wf_$1"_finished.json)
+            if [[ $finished_wf_status != "success" ]]; then
+              echo "workflow we were waiting for has failed, exiting. This pipeline will not continue."
+              exit 1
+            fi
+
             echo "No other workflows detected. Releasing hold."
             exit 0
           else
