[semver:minor] use non deprecated auth method and improve output

diff --git a/src/commands/wait_for_workflow.yml b/src/commands/wait_for_workflow.yml
--- a/src/commands/wait_for_workflow.yml
+++ b/src/commands/wait_for_workflow.yml
@@ -53,7 +53,7 @@ steps:
         fi
 
         hash jq 2> /dev/null || {
-          echo >&2 "jq is not installed.  Aborting."
+          echo >&2 "jq is not installed. Aborting."
           exit 1
         }
 
@@ -80,20 +80,20 @@ steps:
         workflow_start_time=""
 
         get_workflow_start_time() {
-          wf_url="https://circleci.com/api/v2/workflow/$1?circle-token=${CIRCLE_TOKEN}"
-          curl -s "$wf_url" > /tmp/swissknife/"wf_$1".json
+          wf_url="https://circleci.com/api/v2/workflow/$1"
+          curl -s --request GET --url "$wf_url" --header "Circle-Token: ${CIRCLE_TOKEN}" > /tmp/swissknife/"wf_$1".json
           workflow_start_time=$(jq '.created_at' /tmp/swissknife/"wf_$1".json)
         }
 
         get_num_running_workflows() {
           running_job_prefix="https://circleci.com/api/v1.1/project/$slug"
-          running_jobs_suffix="?circle-token=${CIRCLE_TOKEN}&filter=running&limit=100"
+          running_jobs_suffix="?filter=running&limit=100"
           running_jobs_branch=""
           if [[ $branch_to_consider != "all" ]]; then
             running_jobs_branch="/tree/$branch_to_consider"
           fi
           running_jobs_url="${running_job_prefix}${running_jobs_branch}${running_jobs_suffix}"
-          curl -s "$running_jobs_url" > /tmp/swissknife/running_jobs.json
+          curl -s --request GET --url "$running_jobs_url" --header "Circle-Token: ${CIRCLE_TOKEN}" > /tmp/swissknife/running_jobs.json
           total_workflows_running=$(jq --arg curworkflow "$CIRCLE_WORKFLOW_ID" '[unique_by(.workflows.workflow_id) | .[] | select(.workflows.workflow_name|test("<< parameters.workflow-name >>")) | select(.workflows.workflow_id|test($curworkflow)|not) ] | length' /tmp/swissknife/running_jobs.json)
           # If no other workflows are running, we're good. just return
           if [ "$total_workflows_running" == "0" ]; then
@@ -108,7 +108,7 @@ steps:
 
           can_i_run="true"
           while IFS= read -r line; do
-            echo "Checking info for workflow:$line"
+            echo -e "\nChecking info for workflow: $line"
             get_workflow_start_time "$line"
             running_wf_start_time=$workflow_start_time
             if [[ $running_wf_start_time = $current_workflow_start_time ]]; then
@@ -119,12 +119,12 @@ steps:
         }
 
         kill_workflow() {
-          echo "Cancelleing workflow by cancelling build ${CIRCLE_BUILD_NUM}"
-          cancel_workflow_url="https://circleci.com/api/v1.1/project/$slug/${CIRCLE_BUILD_NUM}/cancel?circle-token=${CIRCLE_TOKEN}"
-          curl -s -X POST "$cancel_workflow_url" > /dev/null
+          echo "Cancelling workflow by cancelling build ${CIRCLE_BUILD_NUM}"
+          cancel_workflow_url="https://circleci.com/api/v1.1/project/$slug/${CIRCLE_BUILD_NUM}/cancel"
+          curl -s -request POST --url "$cancel_workflow_url" --header "Circle-Token: ${CIRCLE_TOKEN}" > /dev/null
           # Give Circle CI enough time to kill this workflow
           sleep 30
-          # If the job wasnt canceled in 30 seconds fail.
+          # If the job wasn't cancelled in 30 seconds fail.
           exit 1
         }
 
@@ -133,10 +133,10 @@ steps:
         while true; do
           get_num_running_workflows
           if [[ $total_workflows_running == "0" || $can_i_run == "true" ]]; then
-            echo "It's finally my turn. Exiting."
+            echo "No other workflows detected. Releasing hold."
             exit 0
           else
-            echo "Looks like $total_workflows_running workflow(s) are still running."
+            echo "Waiting for $total_workflows_running workflow(s)."
             echo "Already slept for ${current_wait_time}s (out of << parameters.max-wait-time >>s limit), going to sleep for << parameters.sleep-time-between-checks >>s before retrying."
             sleep "<< parameters.sleep-time-between-checks >>"
             current_wait_time=$(( current_wait_time + << parameters.sleep-time-between-checks >> ))
